spring.application.name=SmartPlacementPortal

spring.datasource.url=jdbc:mysql://localhost:3306/smart_placement_portal
spring.datasource.username=root
spring.datasource.password=Root@1331sql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp